index:
    path: /inicio
    controller: App\Controller\HomeController::index

animales:
    path: /animales/{nombre}/{apellidos}
    controller: App\Controller\HomeController::animales
    defaults: { nombre: 'Irene', apellidos: 'Olmos'}
    methods: [GET]
    requirements:
      nombre: '[a-zA-Z ]+'
      apellidos: '[a-zA-Z ]+'

redirigir:
    path: /redirigir
    controller: App\Controller\HomeController::redirigir

animal_index:
    path: /animal/index
    controller: App\Controller\AnimalController::index

animal_save:
    path: /animal/save
    controller: App\Controller\AnimalController::save

# animal_find_one_by_condition:
#     path: /animal/find_one_by_condition
#     controller: App\Controller\AnimalController::find_one_by_condition

# animal_find_by_condition:
#     path: /animal/find_by_condition
#     controller: App\Controller\AnimalController::find_by_condition

animal_detail:
    path: /animal/{id}
    controller: App\Controller\AnimalController::animal
