index:
    path: /inicio
    controller: App\Controller\HomeController::index

animales:
    path: /animales/{nombre}/{apellidos}
    controller: App\Controller\HomeController::animales
    defaults: { nombre: 'Irene', apellidos: 'Olmos'}