index:
    path: /inicio
    controller: App\Controller\HomeController::index

animales:
    path: /animales/{nombre}/{apellidos}
    controller: App\Controller\HomeController::animales
    defaults: { nombre: 'Irene', apellidos: 'Olmos'}
    methods: [GET]
    requirements:
      nombre: '[a-zA-Z ]+'
      apellidos: '[a-zA-Z ]+'

redirigir:
    path: /redirigir
    controller: App\Controller\HomeController::redirigir

animal_index:
    path: /animal/index
    controller: App\Controller\AnimalController::index

animal_irene_find_one_by_condition:
    path: /animal/irene_find_one_by_condition
    controller: App\Controller\AnimalController::irene_find_one_by_condition

animal_irene_find_by_condition:
    path: /animal/irene_find_by_condition
    controller: App\Controller\AnimalController::irene_find_by_condition

animal_irene_find_by_query_builder:
    path: /animal/irene_find_by_query_builder
    controller: App\Controller\AnimalController::irene_find_by_query_builder

animal_irene_find_by_query_builder_using_repo:
    path: /animal/irene_find_by_query_builder_using_repo
    controller: App\Controller\AnimalController::irene_find_by_query_builder_using_repo

animal_irene_find_by_DQL:
    path: /animal/irene_find_by_DQL
    controller: App\Controller\AnimalController::irene_find_by_DQL

animal_irene_find_by_SQL:
    path: /animal/irene_find_by_SQL
    controller: App\Controller\AnimalController::irene_find_by_SQL

animal_save:
    path: /animal/save
    controller: App\Controller\AnimalController::save
    methods: [POST]

animal_detail:
    path: /animal/{id}
    controller: App\Controller\AnimalController::animal

animal_update:
    path: /animal/update/{id}
    controller: App\Controller\AnimalController::update

animal_delete:
    path: /animal/delete/{id}
    controller: App\Controller\AnimalController::delete

crear_animal:
    path: /crear-animal
    controller: App\Controller\AnimalController::crearAnimal

